### ISSUE TITLE
Feature Request: User Feedback

### ISSUE THREAD

**Issue by opcon** [getsentry/raven-csharp#150]
Are there any plans to support submitting User Feedback [[1](https://blog.sentry.io/2016/04/21/introducing-user-feedback.html), [2](https://docs.sentry.io/hosted/learn/user-feedback/)] from the C# client? The current implementation for other clients shows a custom webpage, which wouldn't always be appropriate from C#.

I suggest two new methods:
- one that obtains the url for the user feedback webpage currently shown through the PHP and Javascript clients, so the developer can show this to the user if they choose,
- one that allows the developer to submit the user feedback form from C# code

I am happy to start work on this if you can point me to the API endpoints used

**Comment by samukce** [comment]
It's a Good suggestion.

**Comment by asbjornu** [comment]
@opcon Great idea. Since presenting a web page is only one of several possible ways to present a user feedback dialogue in C#, perhaps a good way to do it would be through a `Func<>` of some sort? I haven't looked at what the server-side expects here, but I assume it's just some sort of string, so as long as the implementation returns a string, it can present a dialogue in whatever means natural in the GUI environment, be it a web page, a WPF window, a console application prompt, or whatever.

I'd happily accept a PR for something like this.

**Comment by opcon** [comment]
Awesome. I have a proof-of-concept working, I'll clean it up and submit the pull request.

**Comment by opcon** [comment]
Just an update on this, I've been super busy with Uni stuff recently but I'll be able to get back to this next week

**Comment by Dids** [comment]
@opcon Still waiting. :)

**Comment by samukce** [comment]
@opcon the next week arrived? =P

**Comment by opcon** [comment]
Next week is here! 😆

I submitted a pull-request, #182

**Comment by asbjornu** [comment]
Fixed in #182.
