### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by hfjallemark** [getsentry/raven-csharp#160]
The last version on Nuget is from april (august if you count pre-release). When will you release a new version? Is there a reason this process is not automated?

**Comment by asbjornu** [comment]
@hfjallemark The last *stable* release was april, yes. But [the latest pre-release](https://www.nuget.org/packages/SharpRaven/2.1.1-unstable0063) is from August 17th. I've wanted thorough testing on it before releasing it, since i contains so many new features. I want to merge in #155 and #156, ship another pre-release of that, give it a couple of weeks and then ship a new stable release.

To help usher out a new release, the best thing you can do is test the pre-release packages. :smiley:

**Comment by marcomorain** [comment]
Didn't realise you were waiting on me. I'll take another pass on
demangling today.

--
  Marc O'Morain
  marc@marcomorain.com



On Fri, 23 Sep 2016, at 09:32, Asbjørn Ulsberg wrote:
> @hfjallemark[1] The last *stable* release was april, yes. But the
> latest pre-release[2] is from August 17th. I've wanted thorough
> testing on it before releasing it, since i contains so many new
> features. I want to merge in #155[3] and #156[4], ship another pre-
> release of that, give it a couple of weeks and then ship a new stable
> release.
> To help usher out a new release, the best thing you can do is test the
> pre-release packages. 😃
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[5], or mute the
> thread[6].
>


Links:

  1. https://github.com/hfjallemark
  2. https://www.nuget.org/packages/SharpRaven/2.1.1-unstable0063
  3. https://github.com/getsentry/raven-csharp/pull/155
  4. https://github.com/getsentry/raven-csharp/pull/156
  5. https://github.com/getsentry/raven-csharp/issues/160#issuecomment-249134162

**Comment by hfjallemark** [comment]
Cool, we'll start using/test the new pre-release since #153 is what we wanted addressed!

**Comment by asbjornu** [comment]
@hfjallemark #153 is not released yet, but I'm shipping out a package just now containing everything done since August 17th, including #153. It will show up on NuGet shortly.

**Comment by hfjallemark** [comment]
Awesome, thanks!

**Comment by asbjornu** [comment]
@hfjallemark: [2.1.1-unstable0079](https://www.nuget.org/packages/SharpRaven.Nancy/2.1.1-unstable0079) is out. Please check it out and report back any issues! :smiley:

**Comment by hfjallemark** [comment]
Will do, thanks again!

**Comment by aldav82** [comment]
I just uploaded the changes requested for #156

**Comment by marcomorain** [comment]
Hi @asbjornu - do you have time to publish a new unstable release? I'd love to test out the callstack-demangling. Thanks!

**Comment by asbjornu** [comment]
@marcomorain: I would if I could, but [CodeBetter's TeamCity server](http://teamcity.codebetter.com/) has been down for over a week now. I've been wanting to move the deploy mechanism over to [AppVeyor](https://www.appveyor.com/), but I haven't found time to do it yet.

**Comment by marcomorain** [comment]
That's cool, I didn't realise your release system was down.

**Comment by asbjornu** [comment]
[Here's the explanation of why it was down](https://blog.jetbrains.com/teamcity/2016/10/hosted-teamcity-for-open-source-a-new-home/).

**Comment by asbjornu** [comment]
@marcomorain: I published [version 2.1.1-unstable0111](http://www.nuget.org/packages/SharpRaven/2.1.1-unstable0111) just now. Please check it out and give feedback.

**Comment by marcomorain** [comment]
👍  will do

**Comment by marcomorain** [comment]
Here is a before/after screen shot of the new demangling in production:

![before](https://cloud.githubusercontent.com/assets/448001/19887855/e84f68e6-a022-11e6-9f22-0c167e255e89.png)

![after](https://cloud.githubusercontent.com/assets/448001/19887857/e9a6acfe-a022-11e6-86b1-57af9826d0ac.png)

🎉

**Comment by asbjornu** [comment]
@marcomorain: Looking good!

**Comment by michaelpinnell** [comment]
Just wanted to bump this (forgive me if posting in a closed thread is a bit of a faux pas) because I really like a lot of the features in the unstable release, but don't feel comfortable updating our production code to make use of it.  Is there a timeline for the next full release, or a laundry list of tasks to be completed prior to it?

**Comment by aldav82** [comment]
I have the same question!

**Comment by asbjornu** [comment]
@michaelpinnell, @aldav82: Sorry, I've just been swamped the last few months so I haven't had free time to dedicate to this. Since we've had the unstable version available for so long and there seems to be no outstanding issues with it, I think we can just merge and do another stable release. I hope to find time for this over the next few days. Thanks for your patience!

**Comment by michaelpinnell** [comment]
No worries, I'm just happy that you were able to respond.  Here's to my (selfish) hope that things calm down for you a bit ^.^

**Comment by asbjornu** [comment]
[Version 2.2 is now finally out](https://www.nuget.org/packages/SharpRaven/2.2.0). Thanks for the patience!

**Comment by michaelpinnell** [comment]
Thanks for the release!
