### ISSUE TITLE
Provide an implementation of ILogger from Microsoft.Extensions.Logging

### ISSUE THREAD

**Issue by LordMike** [getsentry/raven-csharp#175]
Building on my comment on #125, support for .NET Core, an implementation that fits in `Microsoft.Extensions.Logging` should be provided. I have created my own project for it, copied the same buildup as from the Debug logger, and called it `Microsoft.Extensions.Logging.Raven`, for which I've attached the relevant source code.

Feel free to use the attached as a base to build an "official" log provider for the MS log framework. :)

In the end, the code can be used like this:

	public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
	{
		loggerFactory.AddConsole(Configuration.GetSection("Logging"));
		loggerFactory.AddRavenLogger(app.ApplicationServices.GetRequiredService<IRavenClient>(), LogLevel.Error);
		loggerFactory.AddDebug();
	
		// .. snip
	}

[Microsoft.Extensions.Logging.Raven.zip](https://github.com/getsentry/raven-csharp/files/750639/Microsoft.Extensions.Logging.Raven.zip)

**Comment by roryprimrose** [comment]
I just blogged about this the other day - https://www.neovolve.com/2018/06/07/ilogger-for-sentry/

That might meet your needs.

**Comment by bruno-garcia** [comment]
We've just released the first preview of the `ASP.NET Core` integration. 

It also brings in the `Microsoft.Extensions.Logging` so that your Informational log messages in the same transaction are sent as breadcrumbs.

It's possible to use only the `Microsoft.Extensions.Logging`, without the _ASP.NET Core_ integration.
There's a [sample of it here](https://github.com/getsentry/sentry-dotnet/tree/master/samples/Sentry.Samples.ME.Logging)

I would love to get some feedback as we work toward a point release:

It's on NuGet: 

**Logging integration: https://www.nuget.org/packages/Sentry.Extensions.Logging/**
ASP.NET Core integration: https://www.nuget.org/packages/Sentry.AspNetCore/
Main SDK (client, etc): https://www.nuget.org/packages/Sentry/


Release on GitHub:
https://github.com/getsentry/sentry-dotnet/releases

Docs:
https://github.com/getsentry/sentry-dotnet/

I'm online on Gitter: https://gitter.im/getsentry/dotnet

**Comment by bruno-garcia** [comment]
We've released the new SDK which solves this issue:

https://github.com/getsentry/sentry-dotnet/releases

https://www.nuget.org/packages/Sentry

I'll close this issue but please feel free to reopen or open one in the new repository if you have any issues integrating. We'll be happy to help you moving over to the new SDK.
