### ISSUE TITLE
Long Term Support for Raven-Csharp

### ISSUE THREAD

**Issue by michaelpinnell** [getsentry/raven-csharp#177]
I've noticed a dearth of development on this repo over the last five months, and while I'm aware that commenting on this without seeing the clear need to start making my own pull requests is rather foolish, I just wanted to see if I could start a conversation with those currently maintaining this project in order to see whether this was something they have not had time to work on currently, or if there are other larger reasons that growth has stymied here.

**Comment by asbjornu** [comment]
Hi, @michaelpinnell. I am the current community maintainer of this repository, with sporadic help from @getsentry. As Sentry doesn't have hired C# developers and I as such don't work for Sentry, this library is supported on a "best effort" basis by me and them. I do it because I love C#, GitHub, open source and think Sentry delivers a brilliant service that the company I work in use as an essential tool to monitor errors in our systems.

The reason "growth has stymied" is partly because I haven't had time to follow up on features as of late. That means I've been unable to spend time implementing features, but I have accepted and merged pull requests and I will continue doing that and release new versions going forward. So if you have pull requests you want to contribute with, they will be highly appreciated and I welcome all contributions no matter how big or small. 😄

**Comment by michaelpinnell** [comment]
Time to put on my big boy pants and start being a contributing member of my community!

**Comment by asbjornu** [comment]
Excellent! :)
