### ISSUE TITLE
Support for web proxy

### ISSUE THREAD

**Issue by asmo9** [getsentry/raven-csharp#207]
Hi guys.

After a first look, I didn't find a way to provide a web proxy to the Sentry client. Did I miss something?

If it's not supported, I can see what I can do in a PR.

Cheers!

**Comment by bruno-garcia** [comment]
Could you please describe your environment? .NET Framework, Mono, OS version, App type: Console app, web app..

Is defining an application-wide proxy an option for you? 

You can define a proxy to be picked up by _HttpWebRequest_ (the current API used by SharpRaven for web requests) [via web/app.config](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/defaultproxy-element-network-settings)

> "The local computer or application config file may specify that a default proxy be used. If the Proxy property is specified, then the proxy settings from the Proxy property override the local computer or application config file and the HttpWebRequest instance will use the proxy settings specified. If no proxy is specified in a config file and the Proxy property is unspecified, the HttpWebRequest class uses the proxy settings inherited from Internet Explorer on the local computer. If there are no proxy settings in Internet Explorer, the request is sent directly to the server."

From [MSDN](https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest(v=vs.110).aspx)

It's also possible to define a machine-wide (machine.config) proxy config so that all .NET apps will use the proxy.

If instead you need to define a different proxy for SharpRaven, to override the proxy already defined on app.config, I believe a code change is necessary.

**Comment by ghost** [comment]
Hi Bruno.

Thanks for your response; and sorry for not getting back to you right away.

I think your solution is great, and should work for most use cases. My scenario is a bit trickier, however.

Here's some info on the app:

**App type:** End-user client
**Framework:** .NET Framework 4.6
**Language:** C#
**Front-end:** WPF
**Supported OS:** Win7 up to Win10

The application already has a mechanism for proxy, which reads the proxy settings from the Windows registry _(proxy settings are applied there by the app installer)_. What I wanted to achieve is to forward these application proxy settings to Sentry. Since it's reading the Windows registry from C# code, going through an `App.config` file is sadly not a good option for my scenario. Since the app is an end-user app, I cannot change the system proxy settings either.

What I really need for my use case is to set the proxy directly from C# code. What I wanted to be able to do is something like this:

```
IWebProxy myProxy = GetMyProxyFromWhateverPlace();
ravenClient.Proxy = myProxy;
ravenClient.Capture(new SentryEvent("Hello World!"));
```

What do you think is the effort required to be able to do this?

Warm regards,
Guillaume

**Comment by asbjornu** [comment]
@asmo9: Having support for a proxy is a good idea. I think exposing an `IRavenClient.Proxy` property seems like a sensible way to do it. Where it'll actually be used is within the [`Requester`](https://github.com/getsentry/raven-csharp/blob/develop/src/app/SharpRaven/Data/Requester.cs) class. A PR for this would be appreciated. 😃

**Comment by dcramer** [comment]
FWIW we're also going to be releasing a standalone service that you can run on your machines that can act as a proxy/relay. If its overly complex to add proxy support to the SDK I'd say to just avoid it, as we're aiming to tackle it as a fix-all.

**Comment by asbjornu** [comment]
The proxy support in .NET's HTTP libraries is pretty simple and solid, so it won't be much code required to add this. Awesome that you're tackling this centrally, though! 👍

**Comment by bruno-garcia** [comment]
We've release the first preview of the new API, which supports Proxy: 

```csharp
using (SentrySdk.Init(o =>
{
    o.Http(h =>
    {
        h.Proxy = new WebProxy("https://localhost:3128");
    });
}))
{
    SentrySdk.CaptureException(new Exception("Something went wrong."));
}
```

If you are using dependency injection and would like not to depend on `SentrySdk`, that's possible too. Please check [the docs](https://github.com/getsentry/sentry-dotnet/).

You can try it by installing the [Sentry package from NuGet](https://www.nuget.org/packages/Sentry/)

We have the [most basic sample here](https://github.com/getsentry/sentry-dotnet/blob/master/samples/Sentry.Samples.Console.Basic/Program.cs), and [another one using some options](https://github.com/getsentry/sentry-dotnet/blob/master/samples/Sentry.Samples.Console.Customized/Program.cs).

We'd love if you could give it a try and let us know what you think.

Release on GitHub:
https://github.com/getsentry/sentry-dotnet/releases

Docs:
https://github.com/getsentry/sentry-dotnet/

I'm online on Gitter: https://gitter.im/getsentry/dotnet if you'd like to reach me.

**Comment by bruno-garcia** [comment]
We've released the new SDK:

https://github.com/getsentry/sentry-dotnet/releases

https://www.nuget.org/packages/Sentry

I'll close this issue but please feel free to reopen or open one in the new repository if you have any issues integrating. We'll be happy to help you moving over to the new SDK.
