### ISSUE TITLE
Could not load file or assembly 'System.Configuration.ConfigurationManager'

### ISSUE THREAD

**Issue by peyman-contribe** [getsentry/raven-csharp#229]
Hi, 
In .net standard, I cannot use ConfigurationManager 4.4.1 because you already give a reference to 4.4.0.
Even if I want to use version 4.4.0 in .net standard I get a runtime error and it cannot load file or assembly... ( I guess v 4.4.0 is not supported by .net core)
In this case, I can't use ConfigurationManager at all. However, I fixed this issue by using IOption and dependency injection.

**Comment by asbjornu** [comment]
Any ideas how to fix this?

**Comment by bruno-garcia** [comment]
Hi @peyman-contribe , it seems you are using .NET Core.

We've just released the first preview of the `ASP.NET Core` integration. It also brings in the `Microsoft.Extensions.Logging` so that your Informational (or whatever level you configure) log messages in the same transaction are sent as breadcrumbs.

I would love to get some feedback as we work toward a point release:

It's on NuGet: https://www.nuget.org/packages/Sentry.AspNetCore/

Release on GitHub:
https://github.com/getsentry/sentry-dotnet/releases

Docs:
https://github.com/getsentry/sentry-dotnet/

I'm online on Gitter: https://gitter.im/getsentry/dotnet if you'd like to reach me

**Comment by bruno-garcia** [comment]
We've released the new SDK which doesn't have dependency to `System.Configuration.ConfigurationManager`.

**Comment by peyman-contribe** [comment]
@bruno-garcia Great! Thanks
