### ISSUE TITLE
No stack traces for intentional error captures

### ISSUE THREAD

**Issue by dcc635** [getsentry/raven-csharp#260]
None of these calls show a stack trace in Sentry:

- `ravenClient.Capture(new SentryEvent(message));`
  - shows the message in Sentry but no stack trace
- `ravenClient.Capture(new SentryEvent(new Exception(message)));`
  - shows the message in Sentry but no stack trace
- `ravenClient.Capture(new SentryEvent(new Exception()));`
  - shows `Exception of type 'System.Exception' was thrown.` in Sentry but no stack trace

Uncaught exceptions show the full stack trace. It'd be nice if these intentional error reports also showed stack traces. My workaround now is to make the messages unique so I can grep where they occur.

**Comment by bruno-garcia** [comment]
Hi @dcc635, that's a fair request. The reason its currently not there when there is no Exception is that the stacktrace is currently pulled out of the exception. 

Could you please describe what kind of app you are building? 
Also, what is the target framework?

We might be able to solve that with `Environment.Stacktrace` or something

**Comment by jviolas** [comment]
Hi ! 
I had the same issue today.
I've search a workaround without touching to SharpRaven code but it was not ideal.

I've managed to make the changes and I'll submit a PR.

@bruno-garcia For info, in my case, it's in the context of a desktop WPF application targeting .net 4.5.2
And I was not able to use `Environment.Stacktrace` because it's a string. I used directly the `StackTrace` class.

**Comment by bruno-garcia** [comment]
Hi @jviolas. Looks good to me but better ask @asbjornu when the PR comes :)
