### ISSUE TITLE
User-created exceptions

### ISSUE THREAD

**Issue by alexanderkyte** [getsentry/raven-csharp#268]
I'd like to create a SentryException object by hand from a json blob. The current API makes that very difficult to do. It *is* a stack trace, just serialized.

**Comment by alexanderkyte** [comment]
Plan:
- Add constructor to SentryStacktrace that takes an array of StackFrame for PR
- Build Frames array (ExceptionFrame) from this array of StackFrame
- Build StackFrame with: https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.stackframe.-ctor?view=netframework-4.7.2#System_Diagnostics_StackFrame__ctor_System_String_System_Int32_

**Comment by bruno-garcia** [comment]
@alexanderkyte sounds like a fair request. I'd be glad to merge a PR.

It's worth noting we've been working on a [new SDK](https://github.com/getsentry/sentry-dotnet). It's an initiative from Sentry to unify the API across all SDKs. First ones are [.NET](https://github.com/getsentry/sentry-dotnet), [Rust](https://github.com/getsentry/sentry-rust) and [JavaScript](https://github.com/getsentry/sentry-javascript).

[`SentryException` is created here](https://github.com/getsentry/sentry-dotnet/blob/4fc99aaabc817a7c8defc505abd6f350704156fd/src/Sentry/Internal/MainExceptionProcessor.cs#L24-L39) and the actual StackTrace is created [here](https://github.com/getsentry/sentry-dotnet/blob/4fc99aaabc817a7c8defc505abd6f350704156fd/src/Sentry/Internal/SentryStackTraceFactory.cs).
Note that the stack trace creation code is [also used outside of the context of an exception](https://github.com/getsentry/sentry-dotnet/blob/96ee054a73cddbd5a53e0d778195aa5c1a415b9f/src/Sentry/Internal/MainSentryEventProcessor.cs#L115-L119) when a flag is set.

We'll be releasing a major version of the new SDK next month.

Just to clarify though: 
* Do you need to create a `SentryException` or only the `StackTrace`? The latter could be used when capturing a message, without an exception.
* What format is the `StackTrace`? It's not a `SentryStackTrace` that was serialized I'm assuming, right?

I wondering where would we add this in the context of the new SDK, if that's interesting to you.

One last note, we plan to support storing a whole event in disk for scenarios like Xamarin where the event is only sent once the app restarts. I wonder what exactly is the use case you have where the stack trace is serialized since this is an interesting topic for us.

**Comment by bruno-garcia** [comment]
Will be tracked here:
https://github.com/getsentry/sentry-dotnet-protocol/issues/24
