### ISSUE TITLE
Question: How to check if error occured while sending error from app to sentry server

### ISSUE THREAD

**Issue by kziajor-zz** [getsentry/raven-csharp#280]
We try to log errors to sentry in one project. From our local machine every error is send to sentry and is logged correctly. But when we run same app with same configuration on client server, sentry do not log any errors. When we generate error in Javascript code on client server everything works fine. So client server has connection with sentry server, but C# app don't send errors to sentry. We don't know why and we don't know how to check if any error is logged by raven-csharp.

**Comment by bruno-garcia** [comment]
@kziajor Unless you are already integrated with and this is a bug report for raven-csharp, I'd suggest you use give it a try with [our current .NET SDK](https://github.com/getsentry/sentry-dotnet) since raven-csharp has been deprecated [see notice on README](https://github.com/getsentry/raven-csharp#note). If the problem persists please raise an issue on that repository.

Also, we'd need more information to help you troubleshoot the issue. Ideally a github repository with a reproducible project, if not possible, at least more details about your setup.
