### ISSUE TITLE
Enable easier event building for context supports

### ISSUE THREAD

**Issue by dcramer** [getsentry/raven-csharp#77]
Right now it seems fairly complex to utilize User/Http contexts. It might make sense to do something similar to the following pattern for APIs:

```
event = Raven.GetEventFromError(...)
event.User = UserInterface(...)
Raven.Send(event)
```

(Pardon my entire lack of familiarity with C# :)

**Comment by asbjornu** [comment]
@dcramer I'm not sure, but I believe #71 covers this quite well and that the latest prerelease of `develop` contains improvements in this area.

**Comment by asbjornu** [comment]
Now that we have [SharpRaven.Nancy](https://www.nuget.org/packages/SharpRaven.Nancy) out with support for capturing HTTP context information from [Nancy](http://nancyfx.org/), I feel we have an idea on how to solve this for different environments. Since HTTP context stuff usually isn't interface based, it's hard to abstract much more, at least until [OWIN](http://owin.org/) is the only interface we need to cater to. I'm therefore closing this.
